# Generated by Django 5.1.3 on 2024-12-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_like_users_alter_board_member'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='like_users',
        ),
        migrations.AddField(
            model_name='board',
            name='like_members',
            field=models.ManyToManyField(default='', related_name='like_member', to='member.member'),
        ),
    ]
